### ISSUE TITLE
Not so sure this is an issue as much as a question

### ISSUE THREAD

**Issue by jokes54321** [philbertphotos/osticket-multildap-auth#1]
This plug-in is exactly what I am looking for. Will it work in version 1.9.14?

Will it accept an email address for the user id? 

We have two domains with overlapping user names, so we need the user id to be the email address.

**Comment by philbertphotos** [comment]
It should work for 1.94 since its the same internals but i can support it.
As for overlapping names ... That is a pain in the butt since ost does not all duplicate user names. I am sure but its not hard to modify for email address auth

**Comment by jokes54321** [comment]
That's good news. I tweaked the validation PHP file to accept an email address for the user name to maintain uniqueness, just need a plug-in to work with that.

The current LDAP plugin on the OST site doesn't seem to want to work with that. It appears it appends the default domain onto the email address (username) when sending to the LDAP server, causing it to come across as user@domain.com@domain.com.

One potential issue is,  one domain hosts a dozen different email addresses, so which domain to validate against could be an issue.

Sent from my Verizon 4G LTE Smartphone

----- Reply message -----
