### ISSUE TITLE
Agents sync but not users

### ISSUE THREAD

**Issue by wizard210** [philbertphotos/osticket-multildap-auth#12]
So I'm still having some issues getting your plugin to work. I'll try to describe what I'm seeing.

I'm receiving errors on the sync. It looks like agents work but not my ldap users.

Sync executed on (February 14 2018 2:29 pm) next execution in (February 14 2018 2:39 pm)Total ldapusers: (0) Total agents: (3) Total Updated Users: (0) Execute Time: (0:00:05.009)

To help in my testing I have three ldap users set up in OsTicket. 

Here is my search filter which works because I did an AD query with it and it returned all my users.

(&(objectCategory=person)(objectClass=user)(!userAccountControl:1.2.840.113556.1.4.803:=2))

Authentication mode is set to staff and client.

Ldap attributes: cn,telephonenumber,physicalDeliveryOfficeName,mail

sync map: name:cn, phone:telephonenumber,office:physicalDeliveryOfficeName,email:mail

ldap sync filter: (&(sAMAccountType=805306368)(mail=*))

Any assistance would be appreciated.

**Comment by philbertphotos** [comment]
This has been fixed in version 1.2.2
