### ISSUE TITLE
Force create users with private registration mode not working

### ISSUE THREAD

**Issue by dundee-81** [philbertphotos/osticket-multildap-auth#14]
In private registration mode the osTicket user account isn't created for users authenticated via LDAP, which don't have osTicket account.
As a result users get only the message about necessity to contact with administrator on login screen.
Despite this the osTicket log shows that user has been authenticated with ldap_login on my domain (see attached screenshot).
I've installed Multi LDAP Authentication and LookupHTTP Passthru Authentication plugins. In Multi LDAP Authentication and Lookup plugin config the option for force client registration is enabled.

![screenshot_1](https://user-images.githubusercontent.com/1324115/36469627-217c4aa2-16e8-11e8-8a66-fe4ac9e1b8f3.jpg)

**Comment by philbertphotos** [comment]
This is built into Osticket with create a work around.

**Comment by niphint** [comment]
> This is built into Osticket with create a work around.

what do you mean by that?
I have this problem too. On the landing page it is saysing that this addon can create users from LDAP.. but how?

**Comment by niphint** [comment]
I still have the problem, that it isn't creating users(guests).
In the sync_mldap you try to do that 
`//Go through and create accounts for new guest users verified in LDAP`

But the select doesn't repeat anything on my settings. In the table ldap_sync there are only guids with IDs with existing users.
So the Select returns 0 rows.

I really like this addon and this was the main feature why i was adding it.
Could you please have a look at it @philbertphotos 
If you need any additional infos, please tell me.

**Comment by philbertphotos** [comment]
I will it works for me and others ... i will have and update soon.

**Comment by philbertphotos** [comment]
Creation on accounts is Enabled in private mode
