### ISSUE TITLE
Uncommented echo

### ISSUE THREAD

**Issue by tauthement** [philbertphotos/osticket-multildap-auth#19]
Hello,

I noticed on line 243 of auth.php that you echo out the SQL statement. This causes the statement to be output on the site. I figured this was unintentional since you commented out other echoes but not this one. 

Have a nice day and thanks for your work!

**Comment by philbertphotos** [comment]
Yea thanks that was for testing and i forgot to remove it ... will update.

**Comment by philbertphotos** [comment]
Updated
