### ISSUE TITLE
Table prefix missing in sync_mldap.php

### ISSUE THREAD

**Issue by tauthement** [philbertphotos/osticket-multildap-auth#20]
I received this error message through the system log:

[SELECT staff.username, ost_staff.email, ost_staff.phone, ost_staff.phone_ext as ext, ost_staff.mobile FROM ost_staff WHERE ost_staff.username IS NOT NULL]

Unknown column 'staff.username' in 'field list'

---- Backtrace ----
#0 (root)/include/mysqli.php(199): osTicket->logDBError('DB Error #1054', '[SELECT staff.u...')
#1 (root)/scp/sync_mldap.php(361): db_query('SELECT staff.us...')
#2 (root)/include/plugins/multi-ldap/auth.php(77): SyncLDAPMultiClass->check_users()
#3 [internal function]: LdapMultiAuthPlugin->onCronProcessed(NULL, Array)
#4 (root)/include/class.signal.php(98): call_user_func_array(Array, Array)
#5 (root)/scp/autocron.php(69): Signal::send('cron', NULL, Array)
#6 {main}

Fix:
Upon inspecting sync_mldap.php, I noticed that "TABLE_PREFIX . " was missing from line 359.

**Comment by tauthement** [comment]
I want to also note that this may have caused an LDAP Sync error in my System Log, as well. It has the same timestamp as the DB error above. Here is the message I received:

Sync executed on (November 13 2018 8:40 am) next execution in (November 13 2018 10:40 am)Total ldapusers: (884) Total agents: (0) Total Updated Users: (0) Execute Time: (0:00:00.389)

**Comment by philbertphotos** [comment]
Send me the DB error so i can do some tests

**Comment by philbertphotos** [comment]
Ohh the prefix is missing .. i will fix that today.

**Comment by philbertphotos** [comment]
FIXED
