### ISSUE TITLE
PHP Fatal error:  Call to a member function checkGroup()

### ISSUE THREAD

**Issue by tpsretard** [philbertphotos/osticket-multildap-auth#23]
Hello i have just tied to get this plug in working.
I have setup everything and when i try to login with an AD User i get a HTTP ERROR 500

In the logs i have the below error

`PHP Fatal error:  Call to a member function checkGroup() on null in /var/www/html/osTicket/include/plugins/multi-ldap/auth.php on line 596, referer: http://192.168.129.205/osTicket/scp/login.php`

it would seem there is nothing to reinitialize the variable $ldap in the function authOrCreate 
And i have no idea how to add it.

**Comment by philbertphotos** [comment]
Looking into this.

**Comment by tpsretard** [comment]
i did some work on it. check out my changes.

**Comment by philbertphotos** [comment]
Fixed.
