### ISSUE TITLE
Php Fatal Error

### ISSUE THREAD

**Issue by cheezpuff1** [philbertphotos/osticket-multildap-auth#24]
Good Afternoon and thank you for your plugin!

After the initial configuration which was as you say easy enough, we are receiving this error when attempting the initial sync:

[20-Jan-2019 21:44:48 UTC] PHP Fatal error:  Uncaught Error: Class 'SyncLDAPMultiClass' not found in C:\inetpub\wwwroot\include\plugins\multi-ldap\auth.php:69
Stack trace:
#0 C:\inetpub\wwwroot\include\class.signal.php(98): LdapMultiAuthPlugin->onCronProcessed(NULL, Array)
#1 C:\inetpub\wwwroot\scp\autocron.php(69): Signal::send('cron', NULL, Array)
#2 {main}
  thrown in C:\inetpub\wwwroot\include\plugins\multi-ldap\auth.php on line 69

Please let me know your thoughts.

**Comment by cheezpuff1** [comment]
Details I neglected to mention: 
PHP Version: 7.0.30
Web Server: IIS 10.0.17763.1

**Comment by philbertphotos** [comment]
Trying copying the file to that folder manually ... Never tested PHP 7 on IIS so the copy command may have failed.

**Comment by philbertphotos** [comment]
Fixed
