### ISSUE TITLE
Mapping of new fields for users

### ISSUE THREAD

**Issue by Ilkein** [philbertphotos/osticket-multildap-auth#27]
Hi,

I would map some of AD fields to osTicket database. First, I've created the form as shown:
![captura de pantalla 2019-02-14 a las 18 08 18](https://user-images.githubusercontent.com/1070270/52807550-0e00d100-308c-11e9-9f93-83007842e8d8.png)

And then, mapped into the plugin
![captura de pantalla 2019-02-14 a las 18 57 35](https://user-images.githubusercontent.com/1070270/52807562-1953fc80-308c-11e9-8fc1-adba182be42d.png)

But only these are appearing:
![captura de pantalla 2019-02-14 a las 19 11 03](https://user-images.githubusercontent.com/1070270/52807687-85366500-308c-11e9-9b02-296764b9d734.png)

The log is:
![captura de pantalla 2019-02-14 a las 19 13 53](https://user-images.githubusercontent.com/1070270/52807926-10175f80-308d-11e9-8a51-b8c9dd35cca7.png)

I've missed something? Best regards,

**Comment by philbertphotos** [comment]
Is this still an issue?

**Comment by philbertphotos** [comment]
This is no longer a problem with the recent updates.
