### ISSUE TITLE
Class 'LDAPMultiAuthentication' not found

### ISSUE THREAD

**Issue by AndreaVeroni** [philbertphotos/osticket-multildap-auth#28]
Trying the plugin on osticket 1.11 and it seems i cannot trigger the sync...
In logs i get "PHP Fatal error:  Class 'LDAPMultiAuthentication' not found in /var/www/html/ostickettest/scp/sync_mldap.php on line 2, referer: https://supporttest/scp/plugins.php?id=5".

Seems like the class 'LDAPMultiAuthentication' isn't imported, but trying including the file auth.php (where the class is actually defined) causes a status 500.

**Comment by philbertphotos** [comment]
This has been corrected.
