### ISSUE TITLE
mysql issue

### ISSUE THREAD

**Issue by acid847** [philbertphotos/osticket-multildap-auth#3]
Hello I have followed the directions but when it tries to sync I get email reports that a table doesnt exist ost_ldap_sync. What do I need to do to get this working?

**Comment by philbertphotos** [comment]
Its supposed to have created the SQL table I have to debug it again but in you know SQL just run this and I will correct the problem in a update.
CREATE TABLE " . TABLE_PREFIX . "ldap_sync (
                  `id` bigint(20) unsigned NOT NULL,
                  `guid` varchar(40) NOT NULL,
                  `updated` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
                  PRIMARY KEY (`id`)
                ) ENGINE=InnoDB DEFAULT CHARSET=utf8;

**Comment by philbertphotos** [comment]
was this a fresh install? Or an upgrade?

**Comment by acid847** [comment]
It was a fresh install and I also added the file you updated 3 days ago, I'll run the SQL command as well and cheers for the fast responses!

**Comment by wizard210** [comment]
I having the same issue as acid847. I created your table like you mentioned. But I have to change your syntax to get it to work.

CREATE TABLE ost_ldap_sync (
id bigint(20) unsigned NOT NULL,
guid varchar(40) NOT NULL,
updated timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
PRIMARY KEY (id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;
