### ISSUE TITLE
Compatibility with the Microsoft LDAP update in March 2020

### ISSUE THREAD

**Issue by herhed** [philbertphotos/osticket-multildap-auth#31]
Hello,

Microsoft will distribute an important LDAP update in March:

https://www.msxfaq.de/windows/sicherheit/ldapenforcechannelbinding.htm

https://portal.msrc.microsoft.com/en-us/security-guidance/advisory/ADV190023

Unfortunately I have not found any information whether osTicket including the multildap-auth plugin is compatible with the new Channel binding Tokens (CBT) LDAP procedure.

If not, there would be no more LDAP logon to the system on March.
Does anyone know if the plugin is compatible or if there will be an update until then?

PS. A big thank you to the developer! We have been using the plugin for a year now and have had no problems with it so far!

Many greetings

**Comment by philbertphotos** [comment]
Well I am super happy it works well for you. As for the March update (dam YOU MICROSOFT) I can tell you with absolute certainty that it will work with whatever changes MS may change or at least a work around.. I depend on this plugin in our environment.

**Comment by philbertphotos** [comment]
From my research all I need to do is support SSL. Wont be a problem.

**Comment by eitanprezes** [comment]
LOL you know that microsoft bought github, right?
