### ISSUE TITLE
Not finding users in child domains

### ISSUE THREAD

**Issue by EBS-DarkD** [philbertphotos/osticket-multildap-auth#33]
Am deploying your mod on osTicket v1.14.1 using PHP 7.3

I've got two child domains as well as the parent
I've configured all the LDAP info for each domain
The binding account has read permissions across all 3 domains at the domain root and the user OU's
Set Authentication and Registration modes to staff and client
Sync is set for every 10 mins

If I type the user login name for the parent domain it finds it ok, gives the search result and if I click it then it auto populates the fields. I'm trying to add agents in from the two child domains and it is not finding them. 

This is probably something I've configured wrong as I had this working in my old helpdesk, but I need some guidance

**Comment by philbertphotos** [comment]
I think I never added it to find Agents in child domains ... I have child domains myself so I will test verify and let you know what I find.

**Comment by philbertphotos** [comment]
Do you need this feature,?

**Comment by philbertphotos** [comment]
This has been fixed. The plugin will allow agents from any child domain,
