### ISSUE TITLE
DB Error #1146

### ISSUE THREAD

**Issue by ScottishSamurai** [philbertphotos/osticket-multildap-auth#35]
Greetings,

I just added and enabled your plugin.  I previously was using the OSTicket plugin for LDAP but just switched to yours in hopes to get better use with "clients", however I am getting email reports with, DB Error #1146. The emails are saying that a table doesn't exist and column is missing.

Table '(our database)_ldap_sync' doesn't exist
Unknown column 'staff.username' in 'field list'

Was the plugin suppose to add the add the table? and I show the column exsists but not showing our database reference. Any ideas?

**Comment by ScottishSamurai** [comment]
Small update. I see that line 371 does not show TABLE_PREFIX for the staff.name

$qry_ostagents = "SELECT staff.username, " . TABLE_PREFIX . "staff.email, "

**Comment by philbertphotos** [comment]
I will update the fix... let me know if all else works. 
It is supposed to create the tables.
The code is there ... I have to test it on a clean setup.

**Comment by philbertphotos** [comment]
function createDBTables() {
		//db_query("DROP TABLE IF EXISTS " . TABLE_PREFIX . "ldap_sync");
		$sqlsync = ("CREATE TABLE " . TABLE_PREFIX . "ldap_sync (
				  `id` bigint(20) unsigned NOT NULL,
				  `guid` varchar(40) NOT NULL,
				  `updated` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
				  PRIMARY KEY (`id`)
				) ENGINE=InnoDB DEFAULT CHARSET=utf8;");
		//$this->logger('warning', 'createDBTables', $sqlsync);
		$result = db_query($sqlsync);
		if ($result) {
			return true;
		}
		return false;
	}

**Comment by philbertphotos** [comment]
Code errors fixed.
