### ISSUE TITLE
Class 'LdapMultiAuthPluginConfig' not found in /var/www/osticket/include/class.plugin.php

### ISSUE THREAD

**Issue by SupportRBS** [philbertphotos/osticket-multildap-auth#37]
No luck with setting up your plugin :(
I can import your plugin, but if I go in there is nothing (status is disabled) after enable it I got a Error 500 
No other plugins are installed.

osTicket-Version | v1.14.3-22-gd4c289ee (d4c289e)
Server-Software | Apache/2.4.46 (Ubuntu)
MySQL-Version | 10.3.25
PHP-Version | 7.3.24-3+ubuntu20.04.1+deb.sury.org+1
Ubuntu Version | 20.04.1

[Tue Nov 10 08:38:37.788161 2020] [php7:error] [pid 1082] [client 10.212.134.201:58188]
PHP Fatal error:  Uncaught Error: Class 'LdapMultiAuthPluginConfig' not found in /var/www/osticket/include/class.plugin.php:484\nStack trace:
\n#0 /var/www/osticket/include/plugins/multi-ldap/auth.php(30): Plugin->getConfig()
\n#1 /var/www/osticket/include/class.plugin.php(147): LdapMultiAuthPlugin->bootstrap()
\n#2 /var/www/osticket/include/class.osticket.php(643): PluginManager->bootstrap()
\n#3 /var/www/osticket/main.inc.php(33): osTicket::start()
\n#4 /var/www/osticket/scp/staff.inc.php(20): require_once('/var/www/ostick...')
\n#5 /var/www/osticket/scp/tickets.php(17): require('/var/www/ostick...')
\n#6 /var/www/osticket/scp/index.php(17): require('/var/www/ostick...')
\n#7 {main}\n  thrown in /var/www/osticket/include/class.plugin.php on line 484

**Comment by olrak2** [comment]
Same error for me on a Windows Server with the latest version of osTicket Core, v1.12.6 installed
![image](https://user-images.githubusercontent.com/17641040/99086952-7dda1d80-25ca-11eb-8931-a87bc0c08e42.png)

**Comment by philbertphotos** [comment]
I dont see how but I checking right now..

**Comment by philbertphotos** [comment]
@olrak2 you missing a file ... make sure all files are in the folder.

**Comment by philbertphotos** [comment]
@olrak2 and @SupportRBS the error has been fixed please update your copies.
