### ISSUE TITLE
Ticket ool www: PHP Fatal error:  Class 'LDAPMultiAuthentication' not found in /var/www/osticket/upload/scp/sync_mldap.php on line 2

### ISSUE THREAD

**Issue by WimTh** [philbertphotos/osticket-multildap-auth#39]
Hi,

When trying to sync users i get this error:
Ticket ool www: PHP Fatal error:  Class 'LDAPMultiAuthentication' not found in /var/www/osticket/upload/scp/sync_mldap.php on line 2
I checked the dir and the file is present.
Info:
osTicket v1.14.3
PHP 7.2.24-0ubuntu0.18.04.7
MySQL 5.7.32
nginx/1.14.0 web server

**Comment by philbertphotos** [comment]
That is weird .. let me check.

**Comment by philbertphotos** [comment]
Are you sure that is all ... is there nothing else in the error log? I made some changes to "config.php" see if if fixes that issue.

**Comment by WimTh** [comment]
Downloaded and installed the latest files but still get the same error.
Regarding other errors, after a reboot i got this error MLA-createSyncTables | Error.
But when i check the db the tables have been created.
Also in the config of the plugin the date and time of the next run is not correct:
Next schedule: January 01 1970 1:00 am
Last run: January 01 1970 1:00 am
I am not sure but it also looks like that the cron job is not scheduled.

**Comment by philbertphotos** [comment]
Erase the error log and repeat the sync and post the log it generates so I can see why it happens I cant duplicate it.

**Comment by olrak2** [comment]
Same error here: also next schedulde error : 

![image](https://user-images.githubusercontent.com/17641040/99368776-db68b580-28bb-11eb-9917-615489e48625.png)

After pushing the sync users button i get this error in my log file:
[17-Nov-2020 09:01:37 UTC] PHP Fatal error:  Uncaught Error: Class 'LDAPMultiAuthentication' not found in C:\inetpub\wwwroot\osTicket\scp\sync_mldap.php:2
Stack trace:
#0 {main}
  thrown in C:\inetpub\wwwroot\osTicket\scp\sync_mldap.php on line 2

**Comment by philbertphotos** [comment]
OK let me try to duplicate this on a fresh system. It has to be something I missed that only happens on a first install.
I will have it fixed today.

**Comment by philbertphotos** [comment]
Ok all done. Forget to add the code for doing user syncs manually.

**Comment by philbertphotos** [comment]
Fixed.
