### ISSUE TITLE
Agent control

### ISSUE THREAD

**Issue by olrak2** [philbertphotos/osticket-multildap-auth#40]
When going to the agent, user management.

It only load's until this ![image](https://user-images.githubusercontent.com/17641040/99261526-22539e00-281d-11eb-878a-2dfa5343b011.png)

An error i get is this : 
[16-Nov-2020 13:54:41 UTC] PHP Fatal error:  Uncaught Error: Using $this when not in object context in C:\inetpub\wwwroot\osTicket\include\plugins\multi-ldap\config.php:21
Stack trace:
#0 C:\inetpub\wwwroot\osTicket\include\plugins\multi-ldap\auth.php(809): LdapMultiAuthPluginConfig::translate()
#1 C:\inetpub\wwwroot\osTicket\include\staff\staff.inc.php(156): StaffLDAPMultiAuthentication->getName()
#2 C:\inetpub\wwwroot\osTicket\scp\staff.php(193): require('C:\\inetpub\\wwwr...')
#3 {main}
  thrown in C:\inetpub\wwwroot\osTicket\include\plugins\multi-ldap\config.php on line 21

**Comment by philbertphotos** [comment]
Ok I will update my local copy from my test server and get back to you on this today.

**Comment by philbertphotos** [comment]
I just fixed this on my live system. Try now and see if it works for you as I test this in development also.

**Comment by olrak2** [comment]
The error is gone now, but now a new error when syncing : 

[16-Nov-2020 15:18:21 UTC] PHP Fatal error:  Uncaught Error: Class 'LDAPMultiAuthentication' not found in C:\inetpub\wwwroot\osTicket\scp\sync_mldap.php:2
Stack trace:
#0 {main}
  thrown in C:\inetpub\wwwroot\osTicket\scp\sync_mldap.php on line 2
[16-Nov-2020 15:18:24 UTC] PHP Warning:  Creating default object from empty value in C:\inetpub\wwwroot\osTicket\include\plugins\multi-ldap\config.php on line 54

**Comment by philbertphotos** [comment]
checking trying to duplicate the error.

**Comment by philbertphotos** [comment]
Try now and see if the change fixes this issue.

**Comment by olrak2** [comment]
Agent controle is working now, i close this ticket.

Thx for the work.
