### ISSUE TITLE
Can't get syncing

### ISSUE THREAD

**Issue by LucaThe** [philbertphotos/osticket-multildap-auth#41]
Hello,

I'm trying to configure multildap on osticket v1.14.3, installed on IIS 10 with PHP 7.3.
I had the 'SyncLDAPMultiClass' not found error but once copied the file manually it disappeared.
Now I have no errors but clicking the sync users button i have no output and i can't find any user added to osticket
What can I to to make it work?

Thank you

I'm attaching config screenshot (obviously some name is edited) (now verbose debug is enabled)

![Capture1](https://user-images.githubusercontent.com/71757308/102522018-f6367180-4095-11eb-95a6-99445ca7b624.PNG)
![Capture2](https://user-images.githubusercontent.com/71757308/102522021-f7679e80-4095-11eb-9e03-8d337e805914.PNG)

**Comment by lucize** [comment]
first try in using ldapsearch tool, also you could use wireshark to see if is working but for windows you should use userforldap@domain.local as search user no the CN type

**Comment by philbertphotos** [comment]
Is this still an issue?

**Comment by logmsf** [comment]
hey @LucaThe have you solved you issue?

I'd be curious what you did to solve it!

**Comment by philbertphotos** [comment]
This has been solved.
