### ISSUE TITLE
email auh and  report address

### ISSUE THREAD

**Issue by lucize** [philbertphotos/osticket-multildap-auth#43]
minor problem - when I want to add an email address it seems that the length is too short or maybe is a bug related to php version  (7.3)  I had to change sync_mailto array length

the original ldap authentication allowed me to login using the email address, this version allows me only to login with username, the email address with the short domain is sent to the AD servers
seems that original ldap is using the filer: Filter: (&(&(objectCategory=person)(objectClass=user))(mail=user@contos.com))

also it seems that TLS checkbox is not doing anything the tcpdump show plain and no ldaps traffic

of course if you have the time to look into this

**Comment by philbertphotos** [comment]
That is weird let me look at the TLS and will look at the email thing. I am sure it drops off the email part so it authenticates by username.

**Comment by lucize** [comment]
yes, it drops the domain part but not always the user has the same username as it's email address, anyhow this is not such a big issue if you use sso

**Comment by philbertphotos** [comment]
Now supports TLS/SSL
