### ISSUE TITLE
Short Domain Binds

### ISSUE THREAD

**Issue by zackchadwick** [philbertphotos/osticket-multildap-auth#45]
I'm making use of 389-DS as my directory server. Unfortunately this plugin tries to authenticate using the short domain, ie user@example.com. 

By default 389-DS requires the full DN, so uid=user,ou=people,dc=example,dc=com to authenticate. Unfortunately there is no setting within the plug specifying how to authenticate. It's odd to me because the search and everything else seems to use the full DN but when you try to log in at the authentication screen for OSTicket it only goes by the short domain.

Would it be possible to have the option on whether to use the fqdn vs the short domain syntax for authentication?

**Comment by philbertphotos** [comment]
Yes that option can be added.

**Comment by philbertphotos** [comment]
@zackchadwick can you show me a login string so i can more understand what you looking for,

**Comment by philbertphotos** [comment]
Close for non response. Will be added in future version
