### ISSUE TITLE
Unable to save settings

### ISSUE THREAD

**Issue by pdklein88** [philbertphotos/osticket-multildap-auth#48]
I have installed and enabled your plugin, however, when I click save changes at the bottom of the configuration page, I get "This page isn’t working ____ is currently unable to handle this request. HTTP ERROR 500"

I am running osTicket version 1.15.1 on Microsoft IIS, PHP 7.3.19, and MySQL 5.5.45.

Thanks
Pete

**Comment by philbertphotos** [comment]
Thats a bug in IIS/PHP you have to manually copy "sync_mldap.php" to the SCP folder.

**Comment by pdklein88** [comment]
Thanks - I gave that a try, but still getting the same error message. Just to be sure I did it correctly, I copy sync_mldap.php from your repository into C:\inetpub\wwwroot\osTicket\scp

**Comment by philbertphotos** [comment]
@pdklein88 i updated the plugin let me know if this works.
