### ISSUE TITLE
It dosn't updating users. 

### ISSUE THREAD

**Issue by oskar15** [philbertphotos/osticket-multildap-auth#50]
Hi, I have a problem with a Plugin. I configured everything and the plugin finds ldapusers but does not synchronize them. 
I'm getting those Errors: 
In osTicket System Log:
Sync executed on (April 22 2022 7:30 am) next execution in (April 22 2022 7:30 am)Total ldapusers: (108) Total agents: (1) Total Updated Users: (0) Execute Time: (0:00:00.011)

and in log file:
[php7:warn] [pid 34288] [client 192.168.178.44:50989] PHP Warning:  Creating default object from empty value in /var/www/osTicket/upload/include/plugins/multi-ldap/config.php on line 57, referer: http://newosticket/scp/plugins.php?id=6

Server Information
--
osTicket Version | v1.15.6 (1a64b84) Upgrade— v1.15.7 is available
Web Server Software | Apache/2.4.41 (Ubuntu)
MySQL Version | 10.3.34
PHP Version | 7.4.3

**Comment by philbertphotos** [comment]
Force the schedule to save in a later update i will force a default this is a bug. updating and doing this should fix the error.

![image](https://user-images.githubusercontent.com/2892474/164934147-a286577e-b02a-4014-b2fa-74a4e4146fc3.png)
