### ISSUE TITLE
Constant reports

### ISSUE THREAD

**Issue by EBS-DarkD** [philbertphotos/osticket-multildap-auth#54]
I've just done a clean install of osTicket 1.16.3 and dropped the latest version of your plugin 1.5.8.

I am now getting reports (for the first time ever but the reported status is showing errors
![image](https://user-images.githubusercontent.com/16149089/173327217-a40abbc8-9187-475a-8ea7-7202cfd646b9.png)

Is this normal or have I a problem here?

**Comment by philbertphotos** [comment]
This does not seem to be an actual error but just informational I updating the plugin so you can turn on and off certain parts of the logging. Right now its just on because of the massive changes to get it compatible with PHP 8.0 ... its annoying but necessary for the time being.

**Comment by philbertphotos** [comment]
@EBS-DarkD recently updated so lots of fixes.
