### ISSUE TITLE
Sync not finding/updating any users, only agents

### ISSUE THREAD

**Issue by dylanglass6300** [philbertphotos/osticket-multildap-auth#55]
Hello,

I am using osTicket v1.16.3, on PHP 8.0.13, using the most recent version of your plugin.

I am able to connect my LDAP server and have it sync properly and on schedule, but it is always pulling 0 users like the screenshot below. My search filter and LDAP sync filter are blank in configuration, so the issue may lie in that. I have also used the default filters that you have set, and they also came back with 0 users.

Let me know if you need any more info from me.

![image](https://user-images.githubusercontent.com/105012534/176008381-00c289f2-5ee7-4573-9e61-45d8c3930f39.png)

**Comment by philbertphotos** [comment]
Look like the newest version is stripping HTML in the logs.
Its very very strange that its able to find agents and not able to find users since they both use the same search string.... but let me see to make sure.

**Comment by berilslv** [comment]
Im facing similar problem using php8.0.13(ubuntu server)
Synced agent count- 3 , but I cant find them in any group/list/organzation.

**Comment by philbertphotos** [comment]
Check by making a change to a user attribute to verify since it looks at that for changes.  If it sees none then there is no need to update

**Comment by philbertphotos** [comment]
This is me ..
It list total ldapusers
total agents
and only the users who have been updated
![image](https://user-images.githubusercontent.com/2892474/189158709-906fd387-6c66-4fe5-b26b-c6d5502b7f5a.png)

**Comment by PaysenPetersen** [comment]
Hello,

i still have the same problem. Agents are syncronized, users are not syncronized. If a new user logs in and writes a ticket, the e-mail address etc. will not be transferred to the database. Until yesterday I had the problem with UTF-8, which you fixed. The connect to both AD' now works perfectly. The registration too. But no synchronization.

Can I provide you with any LOG files?

![image](https://user-images.githubusercontent.com/67009826/192477058-350a2516-20ee-4adb-b590-291f6249463a.png)

**Comment by philbertphotos** [comment]
@PaysenPetersen Yes send me logs files you have....
So question for example if I edit any bit of information in this user on the next sync it updates the user. Cant you try that? 
![image](https://user-images.githubusercontent.com/2892474/194629517-8dbd54aa-654f-4a12-9ae8-e6aa62f42081.png)

**Comment by philbertphotos** [comment]
@PaysenPetersen This should be fixed now updated lots of bits so it actually supports 1.16 and 1.17
