### ISSUE TITLE
LDAP and PHP Errors

### ISSUE THREAD

**Issue by siilitman** [philbertphotos/osticket-multildap-auth#65]
Upgraded my OSTicket from 1.15.8 to 1.17.2 and flipped the php to 8.1

Initially, I couldn't access the site due to a php error with a miss match between getconfig($id) and getconfig()
My eventual fix for that was to edit ./scp/sync_mldap.php line 116 and remove the $id
The site started working and I was able to login.

I'm now facing the issue of any LDAP activity throws an error in the logs and often doesn't work or display results
I'm seeing this in the apache error logs
Uncaught TypeError: trim(): Argument #1 ($string) must be of type string, array given in /var/www/html/help/include/class.format.php:148\nStack trace:\n#0
Uncaught Error: Class "LDAPMultiAuthentication" not found in /var/www/html/help/scp/sync_mldap.php:2\nStack trace:\n#0 {main}\n

What should I be looking at to narrow this down a bit?

**Comment by philbertphotos** [comment]
I have not tested it in 1.17.2 I will do that today and get back to you.
Did you update the plugin to the latest version and delete the sync_mldap.php first so it would be forced to update.

**Comment by philbertphotos** [comment]
As you can see line 116 does not have any $id so I am sure its a old copy of the plugin and it should work with 1.17.2 with no issues since the changes wont affect how the plugin works.
![image](https://user-images.githubusercontent.com/2892474/212930289-661e13aa-6fa5-4832-ae06-a6fe6bbdc211.png)

**Comment by siilitman** [comment]
I did upgrade the plugin as I upgraded the OSTicket but I didn’t know about deleting the sync_mldap.php!

Andy Baker
IT Technical Lead
SIIL Corporate IT

***@***.***

Salam International Investments Ltd.
Maysaloun Street - West Bay | Salam Plaza Tower, 3rd Floor | PO Box: 15224, Doha – Qatar
Tel: +974-44838733, Direct: +974-44485711
E-mail: ***@***.******@***.***>
Website: www.salaminternational.com<http://www.salaminternational.com/>

**Comment by philbertphotos** [comment]
@siilitman its a stupid bug that affects some systems. I have checks and balances but some times it wont allow the PHP to delete and copy the new file like it should.

**Comment by philbertphotos** [comment]
FIXED
