### ISSUE TITLE
Email report sends plain search user password

### ISSUE THREAD

**Issue by Fe3lApAcUt** [philbertphotos/osticket-multildap-auth#68]
Hey

When I received report mails today, it contained the plain ldap search user password. 
My suggestion is to remove the password completely or replace it with a placeholder. 

BR Marcel

**Comment by philbertphotos** [comment]
Wait WHAT.... its never designed to do that! Let me look at this QUICK!

**Comment by Fe3lApAcUt** [comment]
I'll leave you a screenshot. I received this mail as an administrator when I searched for a user in the the user management

![image](https://user-images.githubusercontent.com/48884553/228447376-fcea41d6-839e-4365-92ef-ea9b5a37af19.png)

**Comment by Fe3lApAcUt** [comment]
the password is also visible in the DB (xx_config)

**Comment by philbertphotos** [comment]
I correcting that bug and also encrypting the password in a future release.

**Comment by philbertphotos** [comment]
@Fe3lApAcUt  are you saying it sent you an email while searching a user name? Or included when sending a report? Is it something that repeats each time you do it?

**Comment by Fe3lApAcUt** [comment]
@philbertphotos it sent me the mails when I started searching for a user.
The reports never worked for me.

**Comment by philbertphotos** [comment]
@Fe3lApAcUt currently testing the new version in my test version than can send emails and will try and duplicate this and then create a patch once I figure out how its happening.

**Comment by philbertphotos** [comment]
Cant duplicate the email you get with searching for users ... but I am removing any debug code and will do a update. I think it may be verbose debug sending the admin email of some kind of error.

**Comment by Fe3lApAcUt** [comment]
Yeah, I think its because of debug, too.

**Comment by philbertphotos** [comment]
Removed debug code should be all good now.
