### ISSUE TITLE
LDAP Search Filter Not Working

### ISSUE THREAD

**Issue by croweda** [philbertphotos/osticket-multildap-auth#7]
I have the multildap-auth plugin installed and it is working fine to authenticate users on 4 different Active Directory domains.  I am also using SSO with the HTTP Passthrough plugin and that too is working fine.  My issue is that I need a few accounts to NOT auto-create a user and request that a user logs in with another account.  These accounts are "general" accounts for multi user workstations.  My plan was to add these general accounts to a group and exclude that group using the LDAP Search Filter, but every attempt I have made has had no affect, it still keeps automatically signing in as the general account and forcing registration as a User in osticket.  I know the LDAP search filter syntax is correct because I can copy and paste it into a custom search in Active Directory and the expected results display (without the generic accounts).

![ldap](https://user-images.githubusercontent.com/32466643/31096075-9ed317e2-a780-11e7-8121-e7b080ec3f8c.jpg)

**Comment by philbertphotos** [comment]
No that wont work it bypasses the filter to add the user this would have to be a feature i add that if the user is not for in the search list that it by passes the user creation

**Comment by croweda** [comment]
I may have to take a look around at the PHP code and see if I can add a few lines that would apply an LDAP Filter before the initial authentication... any recommendations as far as what file/line to focus on? My guess would be the class.AuthLdap.php file, but that is just a hunch at this point... If i get it figured out, I'll share the code with you and you can build a user friendly way of including it in the plugin.

**Comment by philbertphotos** [comment]
No everything you need is in auth.php

**Comment by philbertphotos** [comment]
Would appreciate your input

**Comment by croweda** [comment]
Thank you, I'll take a look and let you know if I figure something out.
