### ISSUE TITLE
DateTimeZone : Unknow or bad timeone()

### ISSUE THREAD

**Issue by jianfzhu** [philbertphotos/osticket-multildap-auth#9]
When i enable Mutil LDAP plugin. the web page can't open. in apache log display
"PHP Fatal error: Uncaught exception 'Exception' with messages 'DateTimeZone: construct(): Unknow or bad timezone()" in plugins/multi-ldap/auth.php:58\nStack trace:\n#0..............

my Environment:  osticket 1.9.16 
        php 5.6.32
        mariadb: 10.1.29

Timezone: Asia/Shanghai
linux date  --> Fri Jan 12 17:00:00 CST 2018

And i setup in osticket 1.10.1. it no error. but no user sync.

**Comment by philbertphotos** [comment]
I cant duplicate that error. Suggestion is to update PHP
On Fri, Jan 12, 2018 at 05:33 AM, "jianfzhu"  wrote: When i enable Mutil LDAP plugin. the web page can't open. in apache log display
 "PHP Fatal error: Uncaught exception 'Exception' with messages 'DateTimeZone: construct(): Unknow or bad timezone()" in plugins/multi-ldap/auth.php:58nStack trace:n#0..............
 my Environment: osticket 1.9.16
 php 5.6.32
 mariadb: 10.1.29
 Timezone: Asia/Shanghai
 linux date --> Fri Jan 12 17:00:00 CST 2018
 And i setup in osticket 1.10.1. it no error. but no user sync.

**Comment by philbertphotos** [comment]
Can you show me what you have actually set in Osticket?

On Fri, Jan 12, 2018 at 05:33 AM, "jianfzhu"  wrote: When i enable Mutil LDAP plugin. the web page can't open. in apache log display
 "PHP Fatal error: Uncaught exception 'Exception' with messages 'DateTimeZone: construct(): Unknow or bad timezone()" in plugins/multi-ldap/auth.php:58nStack trace:n#0..............
 my Environment: osticket 1.9.16
 php 5.6.32
 mariadb: 10.1.29
 Timezone: Asia/Shanghai
 linux date --> Fri Jan 12 17:00:00 CST 2018
 And i setup in osticket 1.10.1. it no error. but no user sync.

**Comment by jianfzhu** [comment]
i re-install it. now it display ost_ldap_sync doesn't exist in system logs.  how to create the table?

**Comment by philbertphotos** [comment]
FIXED in the new version.
